# TCL File Generated by Component Editor 10.1sp1
# Thu Mar 14 14:49:30 MDT 2013
# DO NOT MODIFY


# +-----------------------------------
# | 
# | encoder "encoder" v1.0
# | null 2013.03.14.14:49:30
# | 
# | 
# | /afs/ualberta.ca/home/j/o/jongeriu/Desktop/AutonomousExplorer/encoder.vhd
# | 
# |    ./encoder.vhd syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 10.1
# | 
package require -exact sopc 10.1
# | 
# +-----------------------------------

# +-----------------------------------
# | module encoder
# | 
set_module_property NAME encoder
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property DISPLAY_NAME encoder
set_module_property TOP_LEVEL_HDL_FILE encoder.vhd
set_module_property TOP_LEVEL_HDL_MODULE encoder
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL TRUE
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file encoder.vhd {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point myclock
# | 
add_interface myclock clock end
set_interface_property myclock clockRate 0

set_interface_property myclock ENABLED true

add_interface_port myclock csi_myclock_clk clk Input 1
add_interface_port myclock csi_myclock_reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point encoder
# | 
add_interface encoder avalon end
set_interface_property encoder addressAlignment DYNAMIC
set_interface_property encoder addressUnits WORDS
set_interface_property encoder associatedClock myclock
set_interface_property encoder burstOnBurstBoundariesOnly false
set_interface_property encoder explicitAddressSpan 0
set_interface_property encoder holdTime 0
set_interface_property encoder isMemoryDevice false
set_interface_property encoder isNonVolatileStorage false
set_interface_property encoder linewrapBursts false
set_interface_property encoder maximumPendingReadTransactions 0
set_interface_property encoder printableDevice false
set_interface_property encoder readLatency 0
set_interface_property encoder readWaitTime 1
set_interface_property encoder setupTime 0
set_interface_property encoder timingUnits Cycles
set_interface_property encoder writeWaitTime 0

set_interface_property encoder ENABLED true

add_interface_port encoder avs_encoder_read_n read_n Input 1
add_interface_port encoder avs_encoder_chipselect chipselect Input 1
add_interface_port encoder avs_encoder_address address Input 2
add_interface_port encoder avs_encoder_readdata readdata Output 32
add_interface_port encoder avs_encoder_writedata writedata Input 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point encoder_input
# | 
add_interface encoder_input conduit end

set_interface_property encoder_input ENABLED true

add_interface_port encoder_input coe_encoder_input_export export Input 1
# | 
# +-----------------------------------
